### ISSUE TITLE
Ceph access volumes from other hosts other than admin

### ISSUE THREAD

**Issue by kacole2** [thecodeteam/vagrant#32] opened 2016-12-15 16:38 UTC
@codenrhoden I've successfully followed your README and was able to `vagrant ssh ceph-admin`, create a new volume, and mount the volume to the container and map in to the host. Everything works as it should.

I'm trying to think of doing this the same way we use demos for ScaleIO. This would require me going to `ceph-server-1` or `ceph-server-2` and issuing the same commands.

I did the following steps:
```
$ vagrant ssh ceph-server-1
$ sudo -i
# docker volume ls
<nothing>
# rexray volume ls
Oops, an error occured!

  invalid format
```

Are the other two nodes not allowed to be used?

**Comment by codenrhoden** [comment] 2016-12-15 17:09
yes, this is by design. It's even called out in the commit message:

>REX-Ray is pre-configured on the ceph-admin node. RBD
mounts should never be done via kernel module on the same nodes running
OSDs.

99% of the time it's probably going to be fine. It would probably be okay to do for demo purposes just so we don't create a bunch of machines. But *technically* it is ill-advised to run the Ceph OSD daemon on the same node as where you do RBD mounts using the RBD kernel module. Doing so risks the chance of deadlock within the kernel, as advised by Red hat. The use of `librbd` is fine, though, which is why HCI works when using something like OpenStack.

I wanted to at least acknowledge best practice before I broke it.

It's funny, though. This is knowledge that is engrained in me from my time working with Cephf or so long. But it's actually hard to find official documentation saying as such. Maybe I'll ping them on IRC to see if it's still true.  It's not listed here: https://access.redhat.com/documentation/en/red-hat-ceph-storage/2.0/paged/release-notes/chapter-6-known-issues, but people still mention it randomly: http://www.virtualtothecore.com/en/adventures-with-ceph-storage-part-6-mount-ceph-as-a-block-device-on-linux-machines/ <-- see the second paragraph...

But to your point, pre-emption is not supported (and it's difficult to say if it will be in the future). You can, however, show that when docker is killed/stopped, you can mount that volume on another host just fine since Docker gracefully unmounts everything when you kill it. SO that's still a viable demo.

I'm curious what @cduchesne would say here.

FWIW, I am actually creating a second "client" node (separate from the Ceph servers) in my Vagrant file for RBD driver testing. No reason I can't do it here. I just started simple.

**Comment by kacole2** [comment] 2016-12-15 18:13
thanks for the explanation. I think my lack of Ceph knowledge is where the trouble is stemming from. Let's not do something in a demo that wouldn't be done in production. 

I guess i need a better understanding of the 3 node environment, architecturally. There are 3 VMs. What are the roles each of them play? Does `ceph-server-1` and `ceph-server-2` only provide storage while the `ceph-admin` has all the tools for consuming storage from those two nodes? If that's the case, would a better demonstration be seeing which host is serving up the volume, then turn off that host to see how the volume can  be served from the other? 

sorry, still learning on this one.

**Closed as completed** 2017-01-24 21:34 UTC
